// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3zXOLNhoskrUFjRqtHQEbg-lQLcoKjwU',
    appId: '1:379621009255:web:a498ed5157efe85a57f1c2',
    messagingSenderId: '379621009255',
    projectId: 'autoamigo-fa173',
    authDomain: 'autoamigo-fa173.firebaseapp.com',
    storageBucket: 'autoamigo-fa173.firebasestorage.app',
    measurementId: 'G-NJFL31MXMR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbSvVoh7ma_-O1UfwQMvREx9B6MDDVS-o',
    appId: '1:379621009255:android:438c3ba1cee5b9a457f1c2',
    messagingSenderId: '379621009255',
    projectId: 'autoamigo-fa173',
    storageBucket: 'autoamigo-fa173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7IeNAg6C0o-u9PvNpowrCqy7JgBXs-aU',
    appId: '1:379621009255:ios:25878dede1f27a7a57f1c2',
    messagingSenderId: '379621009255',
    projectId: 'autoamigo-fa173',
    storageBucket: 'autoamigo-fa173.firebasestorage.app',
    iosBundleId: 'com.example.autoamigo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7IeNAg6C0o-u9PvNpowrCqy7JgBXs-aU',
    appId: '1:379621009255:ios:25878dede1f27a7a57f1c2',
    messagingSenderId: '379621009255',
    projectId: 'autoamigo-fa173',
    storageBucket: 'autoamigo-fa173.firebasestorage.app',
    iosBundleId: 'com.example.autoamigo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3zXOLNhoskrUFjRqtHQEbg-lQLcoKjwU',
    appId: '1:379621009255:web:00671f34c8b2662e57f1c2',
    messagingSenderId: '379621009255',
    projectId: 'autoamigo-fa173',
    authDomain: 'autoamigo-fa173.firebaseapp.com',
    storageBucket: 'autoamigo-fa173.firebasestorage.app',
    measurementId: 'G-JC33FK0LHZ',
  );
}
